# Files and directories #######################################################
#
# Uses XDG Base Dir spec -  https://specifications.freedesktop.org/basedir/latest/
#
music_directory			"~/Music"
playlist_directory		"~/.local/share/mpd/playlists"
db_file					"~/.local/share/mpd/database"
state_file				"~/.local/state/mpd/state"
sticker_file			"~/.local/share/sticker.sql"
bind_to_address			"any"
log_level				"verbose"
auto_update				"no"
auto_update_depth 		"4096"
follow_outside_symlinks "yes"
follow_inside_symlinks	"yes"
filesystem_charset		"UTF-8"
restore_paused			"yes"

# Input #######################################################################
#
input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

#
###############################################################################

# Audio Output ################################################################
#
audio_output {
    type	"pipewire"
    name	"PipeWire"
    replay_gain_hander	"software"
    mixer_type	"hardware"
}

audio_output {
	type	"fifo"
	name	"fifo output"
	path	"/tmp/mpd.fifo"
	format	"4410:16:2"
}
#
###############################################################################
