###############################
#
# mgr
#
#

[[mgr.prepend_keymap]]
on		= "<Enter>"
desc	= "Enter the child directory, or open the file"
run  	= "plugin smart-enter"

[[mgr.prepend_keymap]]
on		= ["r", "a"]
desc	= "rice - Add or update a dotfile to chezmoi"
run		= "shell --block -- chezmoi add %s"

[[mgr.prepend_keymap]]
on		= ["r", "f"]
desc	= "rice - forget a dotfile in chezmoi"
run		= "shell --block -- chezmoi forget %s"


################################
#
# Input
#
#

[[input.prepend_keymap]]
on		= "<Esc>"
desc	= "Cancel input"
run		= "close"
